### ISSUE TITLE
LUA-Error on start

### ISSUE THREAD

**Issue by TRANCEMANIAC-DE** [gOOvER/Name2Chat#11]
The following LUA-Error pops up when loged in with my character:

Message: Interface/AddOns/Name2Chat/Name2Chat.lua:143: Cannot find a library instance of "AceDBOptions-3.0".
Time: Wed Nov  2 15:37:15 2022
Count: 1
Stack: Interface/AddOns/Name2Chat/Name2Chat.lua:143: Cannot find a library instance of "AceDBOptions-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/AstralKeys/Libs/LibStub/LibStub.lua"]:38: in function `LibStub'
[string "@Interface/AddOns/Name2Chat/Name2Chat.lua"]:143: in function <Interface/AddOns/Name2Chat/Name2Chat.lua:138>
[string "=[C]"]: ?
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:70: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:623: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:615>

Locals: <none>

![Screenshot_20221102_154108](https://user-images.githubusercontent.com/117291496/199519541-7c18b245-d8b1-49e4-8c9c-5e3415c0b315.png)

**Comment by gOOvER** [comment]
pls use latest Version. This error is allready fixed
