### ISSUE TITLE
Name2chat not available ingame, while addon is enabled

### ISSUE THREAD

**Issue by ItMeAedri** [gOOvER/Name2Chat#12]
**Describe the bug**
Name2Chat is enabled.
Logged into the game, attempt to use /n2c or /name2chat command.
Game reponse is that there is no such command.
When looking into game options -> addons there is no name2chat addon.

**To Reproduce**
1. Log onto a character
2. Type /n2c or /name2chat

**Expected behavior**
I expect some sort of Name2Chat interface to pop up.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 10 10.0.19044 N/A Build 19044
 - Game: World of Warcraft
 - Version: 10.0.x

**Comment by gOOvER** [comment]
There is no interface. You find the Config in Option Tab

**Comment by ItMeAedri** [comment]
![Capture1](https://user-images.githubusercontent.com/118159306/201600406-eaba64af-c6a2-49b7-ae11-58a583525eec.JPG)

Doesn't seem to be present as an option.

**Comment by gOOvER** [comment]
yep, its not loaded

**Comment by ItMeAedri** [comment]
![Capture2](https://user-images.githubusercontent.com/118159306/201600612-db122ea3-6efe-442d-b28b-86d29b259ae4.JPG)

**Comment by ItMeAedri** [comment]
Curseforge.

**Comment by gOOvER** [comment]
![Wow_1B9iOH6Y5N](https://user-images.githubusercontent.com/116325/201600750-a9598be7-b8c9-40bc-a83f-6cf1f6739af8.png)

**Comment by ItMeAedri** [comment]
I get it should be loaded. As you see I have the addon enabled in my addon list, but it is not loading.

**Comment by gOOvER** [comment]
install bugsack and buggrabber and take a look, if any error comes up

**Comment by ItMeAedri** [comment]
![Capture3](https://user-images.githubusercontent.com/118159306/201601389-d1437261-0e04-4d1a-a6af-28d76a44a4af.JPG)
Buggrabber grabs this straight away.

Nice and quick response by the way :)

**Comment by gOOvER** [comment]
Thats an old error :/ it should be fixed allready. Which version is installed?

**Comment by ItMeAedri** [comment]
Curseforge says Name2Chat-3.3.3.zip.

**Comment by gOOvER** [comment]
This lib is not longer used:
https://github.com/gOOvER/Name2Chat/blob/master/embeds.xml

**Comment by gOOvER** [comment]
> Curseforge says Name2Chat-3.3.3.zip.

This is the latest. But it looks like, thats not updated for you? did you check "Install libs seperate"?

**Comment by ItMeAedri** [comment]
That is unchecked. Want me to check it?

**Comment by gOOvER** [comment]
https://github.com/gOOvER/Name2Chat/commit/11ee346dc59dc1dac675f8c0fd0d08d7b888947d

**Comment by gOOvER** [comment]
![explorer_qyKbwe21qZ](https://user-images.githubusercontent.com/116325/201602847-5779649c-156d-40e4-ac5e-ee9a892d3fa2.png)

and its not installed 

![Code_4FW94IQVVn](https://user-images.githubusercontent.com/116325/201602947-ae2dd176-c859-402d-b630-c51cbcdbb148.png)

**Comment by gOOvER** [comment]
try to reinstall the addon

**Comment by ItMeAedri** [comment]
Reinstalling the addon doesn't seem to work.
I checked my folder and it seems similar?
![Capture4](https://user-images.githubusercontent.com/118159306/201603835-8fbc2efa-ba3a-479c-b944-c6f6c0173553.JPG)

**Comment by gOOvER** [comment]
can you show me the: 

embeds.xml

?

**Comment by ItMeAedri** [comment]
![Capture5](https://user-images.githubusercontent.com/118159306/201604185-9bc3707b-1380-4414-a6e8-68b9ad84d6e1.JPG)

**Comment by gOOvER** [comment]
I'm dump :/ Give me 5 min to fix it. My fail :)

ty for reporting

**Comment by ItMeAedri** [comment]
Cheers, will update when it gets online.

**Comment by gOOvER** [comment]
![Uploading chrome_bddQK0Uz5y.png…]()

**Comment by gOOvER** [comment]
![chrome_bddQK0Uz5y](https://user-images.githubusercontent.com/116325/201607331-46982d11-2fe0-48bf-b1c6-c9e3194a769f.png)

**Comment by gOOvER** [comment]
Wait for 3.3.5. I re-added all libs to prevent errors

**Comment by gOOvER** [comment]
fixed with https://github.com/gOOvER/Name2Chat/releases/tag/3.3.5
