### ISSUE TITLE
Won't load after addon reinstall

### ISSUE THREAD

**Issue by neosalvo** [gOOvER/Name2Chat#13]
**Describe the bug**
I wiped my interface,wtf, and cache folders for a clean slate for Dragonflight. Now after reinstalling N2C, it won't load into the addon list or come up by the n2c/name2chat command. Tried a few different versions from Curseforge and even installed the latest directly from github...even copy pasted the backed up copy of the addon from before the wipe.

**Buggrabber**
5x Interface/AddOns/Name2Chat/Name2Chat.lua:140: Cannot find a library instance of "AceDB-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/Auctionator/Libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/Name2Chat/Name2Chat.lua"]:140: in function <Interface/AddOns/Name2Chat/Name2Chat.lua:138>
[string "=[C]"]: ?
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

**Additional context**
I did try enabling install libs separately and that didn't resolve the issue.

**Comment by neosalvo** [comment]
Ok...just after posting this it occurred to me to see if it is possible to download the ACE libraries separately. I found ACE3 on Curseforge, installed it, and now the addon is working. That shouldn't be necessary though, right?

**Comment by gOOvER** [comment]
> **Describe the bug** I wiped my interface,wtf, and cache folders for a clean slate for Dragonflight. Now after reinstalling N2C, it won't load into the addon list or come up by the n2c/name2chat command. Tried a few different versions from Curseforge and even installed the latest directly from github...even copy pasted the backed up copy of the addon from before the wipe.
> 
> **Buggrabber** 5x Interface/AddOns/Name2Chat/Name2Chat.lua:140: Cannot find a library instance of "AceDB-3.0". [string "=[C]"]: in function `error' [string "@Interface/AddOns/Auctionator/Libs/LibStub/LibStub.lua"]:23: in function `LibStub' [string "@Interface/AddOns/Name2Chat/Name2Chat.lua"]:140: in function <Interface/AddOns/Name2Chat/Name2Chat.lua:138> [string "=[C]"]: ? [string "@Interface/AddOns/Details/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:61> [string "@Interface/AddOns/Details/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon' [string "@Interface/AddOns/Details/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
> 
> **Additional context** I did try enabling install libs separately and that didn't resolve the issue.

Update to latest release, then it works

**Comment by gOOvER** [comment]
fixed with 3.4.0
