### ISSUE TITLE
Lua Warning

### ISSUE THREAD

**Issue by Axim919** [gOOvER/Name2Chat#14]
**Describe the bug**

For some reason since the 15th when WOW released the beta or whatever this is, my name2chat crashes. Here is a copy of what it is doing - 

**Message: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
Time: Thu Nov 17 22:19:11 2022
Count: 1
Stack: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/Details/Libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/Name2Chat/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:7: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "AceGUI-3.0"."**

**To Reproduce**

There is nothing to do - It simply shows the error above every time I log in and it doesn't work

I should also note that i have uninstalled it and reinstalled it with curseforge and manually. I have also recreated the retail/interface, cache and wtf directories. Lastly, I have tried it without any other addon and nothing makes a difference.

**Desktop (please complete the following information):**
Windows 11

**Additional context**
Thank you

**Comment by gOOvER** [comment]
Do you use the lastest Version? Because the lib is shipped with the addon. From where did you dl the Addon? I give no Support, when its downloaded with WoWUp

**Comment by Elleyon** [comment]
I'm seeing this error >> Message: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
When using >> Name2Chat-3.4.0.zip
Downloaded from >> https://www.curseforge.com/wow/addons/name2chat/download
Notes >> This is on a fresh install of WoW on a new PC.

**Comment by gOOvER** [comment]
> 

can you post the whole error?  There are parts missing.

**Comment by Elleyon** [comment]
Sure, full details below. Let me know if you need anything else.
---------------
1/4
Message: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
Time: Sat Nov 19 10:35:19 2022
Count: 1
Stack: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/Name2Chat/libs/LibStub/LibStub.lua"]:38: in function `LibStub'
[string "@Interface/AddOns/Name2Chat/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:7: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "AceGUI-3.0"."
---------------
2/4
Message: Interface/AddOns/Name2Chat/Name2Chat.lua:140: Cannot find a library instance of "AceDB-3.0".
Time: Sat Nov 19 10:35:19 2022
Count: 1
Stack: Interface/AddOns/Name2Chat/Name2Chat.lua:140: Cannot find a library instance of "AceDB-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/Name2Chat/libs/LibStub/LibStub.lua"]:38: in function `LibStub'
[string "@Interface/AddOns/Name2Chat/Name2Chat.lua"]:140: in function <Interface/AddOns/Name2Chat/Name2Chat.lua:138>
[string "=[C]"]: ?
[string "@Interface/AddOns/Name2Chat/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <.../AddOns/Name2Chat/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Name2Chat/libs/AceAddon-3.0/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/Name2Chat/libs/AceAddon-3.0/AceAddon-3.0.lua"]:619: in function <.../AddOns/Name2Chat/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>
---------------
3/4
Message: Interface/AddOns/Name2Chat/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1 (null)
Time: Sat Nov 19 10:35:19 2022
Count: 1
---------------
4/4
Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/Name2Chat/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1 (null)
Time: Sat Nov 19 10:35:19 2022
Count: 1
---------------

**Comment by gOOvER** [comment]
Please wait round about 15 till 20 mins and test 3.4.2

**Comment by gOOvER** [comment]
Should be online now

**Comment by Elleyon** [comment]
I've fully tested twice with the files extracted from Name2Chat-3.4.2.zip and I'm still getting errors. I can now use **/n2c** and it will give me the help text prompts, but I'm still getting errors on load and errors when attempting **/n2c config** command.

I'll post the full errors below in a minute.

**Comment by Elleyon** [comment]
Errors on load and from /reload:

1/4
```
Message: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
Time: Sat Nov 19 11:41:33 2022
Count: 1
Stack: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/Name2Chat/libs/LibStub/LibStub.lua"]:38: in function `LibStub'
[string "@Interface/AddOns/Name2Chat/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:7: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "AceGUI-3.0"."
```

2/4
```
Message: Interface/AddOns/Name2Chat/Name2Chat.lua:152: Cannot find a library instance of "AceConfigDialog-3.0".
Time: Sat Nov 19 11:41:33 2022
Count: 1
Stack: Interface/AddOns/Name2Chat/Name2Chat.lua:152: Cannot find a library instance of "AceConfigDialog-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/Name2Chat/libs/LibStub/LibStub.lua"]:38: in function `LibStub'
[string "@Interface/AddOns/Name2Chat/Name2Chat.lua"]:152: in function <Interface/AddOns/Name2Chat/Name2Chat.lua:138>
[string "=[C]"]: ?
[string "@Interface/AddOns/Name2Chat/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <.../AddOns/Name2Chat/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Name2Chat/libs/AceAddon-3.0/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/Name2Chat/libs/AceAddon-3.0/AceAddon-3.0.lua"]:619: in function <.../AddOns/Name2Chat/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>
```

3/4
```
Message: Interface/AddOns/Name2Chat/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1 (null)
Time: Sat Nov 19 11:41:33 2022
Count: 1
```

4/4
```
Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/Name2Chat/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1 (null)
Time: Sat Nov 19 11:41:33 2022
Count: 1
```

**Comment by gOOvER** [comment]
i cant confirm; i dont have this error and nothing was changed in code for this lib

**Comment by Elleyon** [comment]
Errors from using **/n2c config** command:

1/5
```
Message: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
Time: Sat Nov 19 11:41:33 2022
Count: 1
Stack: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/Name2Chat/libs/LibStub/LibStub.lua"]:38: in function `LibStub'
[string "@Interface/AddOns/Name2Chat/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:7: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "AceGUI-3.0"."
```

2/5
```
Message: Interface/AddOns/Name2Chat/Name2Chat.lua:152: Cannot find a library instance of "AceConfigDialog-3.0".
Time: Sat Nov 19 11:41:33 2022
Count: 1
Stack: Interface/AddOns/Name2Chat/Name2Chat.lua:152: Cannot find a library instance of "AceConfigDialog-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/Name2Chat/libs/LibStub/LibStub.lua"]:38: in function `LibStub'
[string "@Interface/AddOns/Name2Chat/Name2Chat.lua"]:152: in function <Interface/AddOns/Name2Chat/Name2Chat.lua:138>
[string "=[C]"]: ?
[string "@Interface/AddOns/Name2Chat/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <.../AddOns/Name2Chat/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Name2Chat/libs/AceAddon-3.0/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/Name2Chat/libs/AceAddon-3.0/AceAddon-3.0.lua"]:619: in function <.../AddOns/Name2Chat/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>
```

3/5
```
Message: Interface/AddOns/Name2Chat/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1 (null)
Time: Sat Nov 19 11:41:33 2022
Count: 1
```

4/5
```
Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/Name2Chat/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1 (null)
Time: Sat Nov 19 11:41:33 2022
Count: 1
```

5/5
```
Message: Interface/AddOns/Name2Chat/Name2Chat.lua:121: attempt to index field 'optionFrames' (a nil value)
Time: Sat Nov 19 11:44:14 2022
Count: 1
Stack: Interface/AddOns/Name2Chat/Name2Chat.lua:121: attempt to index field 'optionFrames' (a nil value)
[string "@Interface/AddOns/Name2Chat/Name2Chat.lua"]:121: in function <Interface/AddOns/Name2Chat/Name2Chat.lua:120>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Name2Chat/libs/AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua"]:136: in function <.../AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua:126>
[string "@Interface/AddOns/Name2Chat/libs/AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua"]:401: in function <.../AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua:327>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Name2Chat/libs/AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua"]:762: in function `HandleCommand'
[string "@Interface/AddOns/Name2Chat/libs/AceConfig-3.0/AceConfigCmd-3.0/AceConfigCmd-3.0.lua"]:774: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5224: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4888: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4924: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals: (*temporary) = <function> defined @Interface/SharedXML/Settings/Blizzard_Deprecated.lua:24
(*temporary) = nil
(*temporary) = "attempt to index field 'optionFrames' (a nil value)"

```

**Comment by gOOvER** [comment]
delete and reinstall the addon. I asked in my guild an noone have this error. So i cant confirm

**Comment by Elleyon** [comment]
Okay, I fixed it (for me) by editing the **embeds.xml** file and changing the loading order of the library files. This is what it looks like for me now:

```
<Ui xsi:schemaLocation="http://www.blizzard.com/wow/ui/ ..\FrameXML\UI.xsd">

  <Script file="libs\LibStub\LibStub.lua"/>
  <Include file="libs\CallbackHandler-1.0\CallbackHandler-1.0.xml"/>
  <Include file="libs\AceAddon-3.0\AceAddon-3.0.xml"/>
  <Include file="libs\AceConsole-3.0\AceConsole-3.0.xml"/>
  <Include file="libs\AceDB-3.0\AceDB-3.0.xml"/>
  <Include file="libs\AceDBOptions-3.0\AceDBOptions-3.0.xml"/>
  <Include file="libs\AceGUI-3.0\AceGUI-3.0.xml"/>
  <Include file="libs\AceConfig-3.0\AceConfig-3.0.xml"/>
  <Include file="libs\AceComm-3.0\AceComm-3.0.xml"/>
  <Include file="libs\AceEvent-3.0\AceEvent-3.0.xml"/>
  <Include file="libs\AceTab-3.0\AceTab-3.0.xml"/>
  <Include file="libs\AceSerializer-3.0\AceSerializer-3.0.xml"/>
  <Include file="libs\AceHook-3.0\AceHook-3.0.xml"/>
  <Include file="libs\AceTimer-3.0\AceTimer-3.0.xml"/>
  <Include file="libs\AceLocale-3.0\AceLocale-3.0.xml"/>
		
</Ui>
```

As you can see, AceGUI-3.0 was moved up a few places to avoid the error where it seems to get referenced before being loaded. If I change it back and reload my UI, the addon error comes back until I re-apply that fix.

**Comment by gOOvER** [comment]
Feel free to open a PR

**Comment by gOOvER** [comment]
fixed in https://github.com/gOOvER/Name2Chat/releases/tag/3.4.3

**Comment by Elleyon** [comment]
I've just tested Name2Chat-3.4.4 as working fine for me - thank you for your time on this :)

**Comment by gOOvER** [comment]
> I've just tested Name2Chat-3.4.4 as working fine for me - thank you for your time on this :)

Perfect. thank you for your help :)
