### ISSUE TITLE
When enabled it shows the name in /1 and /2. 

### ISSUE THREAD

**Issue by oliverGreo** [gOOvER/Name2Chat#16]
When enabled it shows the name in /1 and /2.

**Comment by Fayreon** [comment]
Not sure if this is a bug or feature, but my chosen name is appearing in Trade, General, etc Zone Channels. This doesn't happen for a couple people I know using the addon, am I missing an option to specify and/or blacklist which channels the addon works in? Is it perhaps an interaction with Prat? Sorry if this isn't the right forum for this.

**Comment by gOOvER** [comment]
there is an option, where to show the name

**Comment by katya450** [comment]
I have the same issue. 
A friend, who has the **exactly** same version (3.5.0) and same **exact** settings (Enable + Guild checked, nothing more) does not have his name shown in General and other public channels, while my name does show in every channel.
There has to be some clitch with some other addons maybe, or some other weirdness going on.

**Comment by gOOvER** [comment]
i cant confirm this. When its a problem with other addons, then i cant do anything
