### ISSUE TITLE
feature request: Ability to add name (or other identifier) to battle.net whispers

### ISSUE THREAD

**Issue by CaptWhyNot** [gOOvER/Name2Chat#5]
For those of us who have multiple WoW accounts under the same battle.net account, it would be nice to have an option to identify which WoW account is whispering, to help clear up confusion for recipients.

**Comment by gOOvER** [comment]
hmmmm, i think, this is not really needed. Main target is, to add the Realname to chat

**Comment by gOOvER** [comment]
ANd btw; the addon dont work with whispers
