### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by Lossibob** [gOOvER/Name2Chat#6]
I've installed the name2chat addon to my WoW character, but I'm not getting the option in either the GUI interface or the slash commands to actually enter my name to the chat. I've tried the suggestions on the CurseForge addon page, but no luck. I also spoke to a friend, who has used the app for years (it's her that told me about the addon) - she said she knew someone a while ago who had the problem, but can't remember which player it was - or what they did to fix it.
On the GUI, , on the addon tab, the name2chat addon doesn't even show - despite the fact that other addons I've installed before and after, don't have the same issue.

Any help or suggestion of what I might be doing wrong - or how to put whatever the problem is right, would be gratefully received.
Thanks for your time and for whatever help you can offer.
Bob

**Comment by gOOvER** [comment]
Pls post the exact error

**Comment by simonka96** [comment]
hey goover,

im having the same problem. the addon installs but doesn't show in the gui, nor does it work if i write /n2c or /name2chat. there is no "error" it simply doesn't show up even if downloaded and activated.

regards

**Comment by Lossibob** [comment]
I did - I've downloaded name2chat. It shows in my addon list at the
charcter-choice part of the game and in the game's main menu of addons, 
but in the interface add don't menu, it doesn't show up - and therefore
also doesn't give me any option to add my name to the chat window. Sorry -
I'm not very tech-friendly, even now lol, but I've followed all the
instructions, both on the curseforge web page for the addon and also from
an in-game friend who uses the adding (the same instructions to be fair),
but all with no luck so far.

Sorry I'm not more help, I've put it as precise as I can. Thank you for
your time and for any advice you're able to offer

Bob

**Comment by S3BViking** [comment]
I had the same issue. It seems to be related to a fresh install of 3.0.1. I removed 3.0.1, installed 3.0.0, logged in and it worked. Then I updated to version 3.0.1, logged in and it still worked. All of this was via the Curseforge client.

Link to other versions: https://www.curseforge.com/wow/addons/name2chat/files

**Comment by simonka96** [comment]
I did what S3BViking said aswell and it worked, however i had to install the file without the -nolib filename addition. I do not know what the difference is, but the default one is nolib, and this doesn't seem to work even with installing 3.0.0 and then updating afterwards
