### ISSUE TITLE
Change github release zipfile format - Support for WoWup Addon manager

### ISSUE THREAD

**Issue by WybeBosch** [gOOvER/Name2Chat#9]
Would it be possible that you would modify your Zip File releases in such as way that WoWup can be used to install your addon from github? (They have support for synced updates via github url) 

Only thing that needs to be changed i think is some folder structure within your zipfile!

Documentation found here
[Folder structure](https://wowup.io/guide/wowup/hub)
[Install from URL using WoWUp](https://wowup.io/guide/get-addons/overview)

example repo made by WoWup:
https://github.com/WowUp/WowUp.Addon

"Basically just requires a zip with a directory in it named the same as the toc, with the addon in that directory, as you would have it in the Addons directory in your client."

If not, its also an option to release the addon on wago addons, they have support for the WoWup client by default, but still provide ad revenue.

**Comment by gOOvER** [comment]
sry, no. I dont want to support WoWUp.

**Comment by WybeBosch** [comment]
Understandable,  thanks for your reaction.
